import streamlit as st
import pandas as pd
import json
import os
from pathlib import Path
from sqlalchemy.orm import Session
from storage.db import SessionLocal, JobOpportunityTable, ApplicationTable, ResumeVariantTable
from storage.crud import get_candidate_profile_data, get_application_analytics
from engines.discovery import discover_job_from_url, run_mock_discovery
from engines.company_intel import run_company_intelligence
from engines.ranking import compute_job_score
from engines.analytics import get_detailed_analytics, compare_offers
from orchestrator import run_application_pipeline

st.set_page_config(
    page_title="JobHunterAI - Career Intelligence Platform",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling
st.markdown("""
<style>
    .main-header {
        font-size: 2.2rem;
        color: #1E3A8A;
        font-weight: 700;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #4B5563;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #F3F4F6;
        padding: 1.25rem;
        border-radius: 0.5rem;
        border-left: 5px solid #2563EB;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
    }
</style>
""", unsafe_allow_html=True)

# Helper function to get DB session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

db = next(get_db())

# Sidebar Configuration
st.sidebar.title("💼 JobHunterAI")
st.sidebar.caption("AI Career Intelligence Platform v4.0")
st.sidebar.markdown("---")

# Quick Discovery trigger
if st.sidebar.button("🔍 Run Auto-Discovery"):
    with st.spinner("Scraping and filtering job boards..."):
        jobs = run_mock_discovery(db)
        st.sidebar.success(f"Discovered {len(jobs)} new opportunities!")

# Manual URL Ingestion
st.sidebar.subheader("🔗 Ingest Job Posting URL")
manual_url = st.sidebar.text_input("Lever / Greenhouse URL", placeholder="https://jobs.lever.co/...")
if st.sidebar.button("Ingest Opportunity") and manual_url:
    with st.spinner("Parsing job specs..."):
        job = discover_job_from_url(db, manual_url)
        st.sidebar.success(f"Ingested [{job.id}] {job.title} at {job.company_name}!")
        st.rerun()

# Main App Layout
st.markdown("<div class='main-header'>Career Intelligence Dashboard</div>", unsafe_allow_html=True)
st.markdown("<div class='sub-header'>Verify evidence, optimize ATS matching, and track application conversion.</div>", unsafe_allow_html=True)

# Tabs
from config import GEN_DIR, APPLY_THRESHOLD

tab_queue, tab_dash, tab_wizard, tab_graph, tab_crm, tab_offers = st.tabs([
    "📋 Daily Briefing & Queue",
    "📊 CRM Analytics", 
    "🎯 Opportunity Wizard & Approval Gate", 
    "🕸️ Knowledge Graph Explorer", 
    "🤝 Recruiter CRM",
    "💰 Offer Evaluator"
])

# 0. Tab: Daily Briefing & Queue
with tab_queue:
    st.header("Daily Career Briefing & Action Queue")
    
    # Trigger Autonomous Daily Loop
    col_trigger1, col_trigger2 = st.columns([2, 1])
    with col_trigger1:
        st.write("Run the autonomous pipeline loop manually to scrape jobs, classify remote tiers, rank tech stack match, and deliver the daily HTML brief.")
    with col_trigger2:
        if st.button("⚡ Trigger Daily Autonomous Loop", use_container_width=True):
            with st.spinner("Executing discovery scraper, dynamic matching ranking, and sending daily briefing report..."):
                from orchestrator import run_daily_autonomous_loop
                res = run_daily_autonomous_loop(db)
                st.success(f"Daily loop run complete! Processed: {res['processed']}, Matched: {res['matched']}, Briefing Delivered: {res['briefing_sent']}")
                st.rerun()

    st.markdown("---")
    
    # Render Latest Daily Briefing HTML
    st.subheader("📰 Latest Daily Career Briefing")
    import glob
    briefing_files = glob.glob(str(GEN_DIR / "daily_briefing_*.html"))
    if briefing_files:
        # Sort to get the latest file
        briefing_files.sort(reverse=True)
        latest_brief = briefing_files[0]
        try:
            with open(latest_brief, "r", encoding="utf-8") as f:
                html_brief = f.read()
            st.components.v1.html(html_brief, height=450, scrolling=True)
        except Exception as e:
            st.error(f"Error loading daily brief: {e}")
    else:
        st.info("No daily briefing reports generated yet. Trigger the daily loop above to build your first report!")
        
    st.markdown("---")
    
    # Application Queue
    st.subheader("📥 Actionable Match Queue")
    st.write("Review auto-tailored application variants generated by the daily loop before final manual submission.")
    
    # Query matching opportunities
    matching_jobs = db.query(JobOpportunityTable).filter(
        JobOpportunityTable.overall_score >= APPLY_THRESHOLD,
        JobOpportunityTable.status == "discovered"
    ).all()
    
    if not matching_jobs:
        st.success("All high-matching jobs have been reviewed! Run auto-discovery or trigger the daily loop to ingest more opportunities.")
    else:
        # Format table data
        queue_data = []
        for j in matching_jobs:
            app = db.query(ApplicationTable).filter(ApplicationTable.job_id == j.id).first()
            status_text = "✅ Ready" if app and app.cover_letter_path else "⏳ Tailoring Pending"
            queue_data.append({
                "ID": j.id,
                "Company": j.company_name,
                "Job Title": j.title,
                "Match Score": f"{j.overall_score}%",
                "Status": status_text
            })
            
        st.dataframe(pd.DataFrame(queue_data), use_container_width=True)
        
        # Action selector
        st.markdown("#### **Quick Review Action Center**")
        selected_queue_id = st.selectbox(
            "Select Opportunity to Review/Approve",
            options=[j.id for j in matching_jobs],
            format_func=lambda x: next(f"{j.company_name} - {j.title} (Score: {j.overall_score}%)" for j in matching_jobs if j.id == x)
        )
        
        if selected_queue_id:
            job_to_review = db.query(JobOpportunityTable).filter(JobOpportunityTable.id == selected_queue_id).first()
            app_to_review = db.query(ApplicationTable).filter(ApplicationTable.job_id == selected_queue_id).first()
            
            if app_to_review:
                col_btn1, col_btn2 = st.columns(2)
                with col_btn1:
                    if st.button("👍 Approve & Mark as Applied", key="approve_app"):
                        job_to_review.status = "applied"
                        app_to_review.status = "Applied"
                        db.commit()
                        st.success(f"Successfully marked application to {job_to_review.company_name} as Applied!")
                        st.balloons()
                        st.rerun()
                with col_btn2:
                    st.caption("Use 'Opportunity Wizard' tab to edit source code and customize materials prior to approval.")
            else:
                if st.button("⚙️ Trigger Manual Tailoring", key="tailor_manual"):
                    with st.spinner("Compiling tailored resume..."):
                        run_application_pipeline(db, selected_queue_id)
                        st.success("Assets compiled successfully!")
                        st.rerun()

# 1. Tab: CRM Analytics
with tab_dash:
    st.header("Funnel Analytics")
    analytics = get_detailed_analytics(db)
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric(label="Total Opportunities Discovered", value=db.query(JobOpportunityTable).count())
    with col2:
        st.metric(label="Applications Submitted", value=analytics["total_applications"])
    with col3:
        st.metric(label="Response Rate", value=f"{analytics['response_rate_percent']}%")
    with col4:
        interviews = analytics["funnel"].get("Interview", 0)
        st.metric(label="Active Interviews", value=interviews)
        
    st.markdown("---")
    
    col_left, col_right = st.columns(2)
    with col_left:
        st.subheader("Application Funnel Distribution")
        if analytics["funnel"]:
            df_funnel = pd.DataFrame(list(analytics["funnel"].items()), columns=["Status", "Count"])
            st.bar_chart(df_funnel.set_index("Status"))
        else:
            st.info("No applications logged yet. Go to the Wizard to apply.")
            
    with col_right:
        st.subheader("Resume Template Effectiveness")
        if analytics["template_performance"]:
            perf_data = []
            for name, stats in analytics["template_performance"].items():
                perf_data.append({
                    "Template": name,
                    "Total Sent": stats["total"],
                    "Converted": stats["converted"],
                    "Conversion Rate": f"{stats['rate_percent']}%"
                })
            st.table(pd.DataFrame(perf_data))
        else:
            st.info("No statistics available. Submit applications to populate.")

# 2. Tab: Opportunity Wizard & Approval Gate
with tab_wizard:
    st.header("Opportunity Tracking & Asset Generator")
    
    jobs = db.query(JobOpportunityTable).all()
    if not jobs:
        st.warning("No opportunities in the database yet. Click 'Run Auto-Discovery' in the sidebar to populate.")
    else:
        job_options = {f"{j.company_name} - {j.title} (ID: {j.id}, Status: {j.status})": j.id for j in jobs}
        selected_job_label = st.selectbox("Select Target Opportunity", list(job_options.keys()))
        selected_job_id = job_options[selected_job_label]
        
        job = db.query(JobOpportunityTable).filter(JobOpportunityTable.id == selected_job_id).first()
        
        # Display Job details
        st.markdown(f"### **{job.title}** at **{job.company_name}**")
        st.caption(f"Source: {job.source} | URL: {job.url if job.url else 'N/A'}")
        
        # In-line Status Modifier
        col_st1, col_st2 = st.columns([1, 2])
        with col_st1:
            status_opts = ["discovered", "applied", "OA", "Interview", "Offer", "Rejected"]
            current_status_idx = status_opts.index(job.status) if job.status in status_opts else 0
            new_status = st.selectbox("Change Status", status_opts, index=current_status_idx)
            if new_status != job.status:
                job.status = new_status
                # If status is applied but no application object exists, create a basic one
                if new_status == "applied":
                    app_exists = db.query(ApplicationTable).filter(ApplicationTable.job_id == job.id).first()
                    if not app_exists:
                        app = ApplicationTable(candidate_id=1, job_id=job.id, status="Applied")
                        db.add(app)
                elif new_status == "Interview":
                    # Update status of application
                    app = db.query(ApplicationTable).filter(ApplicationTable.job_id == job.id).first()
                    if app:
                        app.status = "Interview"
                db.commit()
                st.success("Opportunity status updated!")
                st.rerun()

        # Job Description Viewer
        with st.expander("Show Job Description Text"):
            st.text(job.jd_text)
            
        st.markdown("---")
        st.subheader("Asset Generation Pipeline")
        
        # Choose Template
        template_name = st.selectbox("Select LaTeX Template Style", ["backend.tex", "frontend.tex", "analytics.tex", "ai.tex", "general.tex"])
        
        col_act1, col_act2 = st.columns(2)
        with col_act1:
            if st.button("🚀 Run Tailoring Orchestrator", use_container_width=True):
                with st.spinner("Processing company news, matching credentials, and optimizing ATS scores..."):
                    res = run_application_pipeline(db, job.id, template_name)
                    if res["success"]:
                        st.success("Assets tailored and validated successfully!")
                        st.balloons()
                        st.rerun()
                    else:
                        st.error(f"Pipeline Execution Failed: {res.get('error')}")
                        if "report" in res:
                            st.subheader("Critic Validation Errors:")
                            for err in res["report"]["errors"]:
                                st.error(err)
                            st.subheader("Critic Warnings:")
                            for warn in res["report"]["warnings"]:
                                st.warning(warn)
                                
        # Render generated assets if they exist
        app = db.query(ApplicationTable).filter(ApplicationTable.job_id == job.id).first()
        if app and app.cover_letter_path:
            st.markdown("### **Review Generated Materials**")
            
            # Sub-tabs for reviewing generated output
            tab_res, tab_cl, tab_net, tab_exp = st.tabs(["📄 Resume Version", "✉️ Cover Letter", "💬 LinkedIn Outreach", "🧠 Explainability Report"])
            
            with tab_res:
                st.info(f"Resume generated under data/generated. Variant ID: {app.resume_variant_id}")
                variant = db.query(ResumeVariantTable).filter(ResumeVariantTable.id == app.resume_variant_id).first()
                if variant:
                    st.text_area("LaTeX Source Code", value=variant.latex_source, height=350)
                    
            with tab_cl:
                if os.path.exists(app.cover_letter_path):
                    with open(app.cover_letter_path, "r", encoding="utf-8") as f:
                        st.markdown(f.read())
                        
            with tab_net:
                if os.path.exists(app.outreach_sequence_path):
                    with open(app.outreach_sequence_path, "r", encoding="utf-8") as f:
                        st.text(f.read())
                        
            with tab_exp:
                safe_company_name = job.company_name.replace(" ", "_")
                exp_path = Path(app.cover_letter_path).parent / f"{safe_company_name}_explainability.json"
                if exp_path.exists():
                    with open(exp_path, "r", encoding="utf-8") as f:
                        exp_data = json.load(f)
                    st.json(exp_data)
                    
                    st.markdown("#### **Selection Decisional Path**")
                    st.write(f"**Job Fit Score**: `{exp_data['decision_parameters']['job_fit_score']}%` (Threshold: `{exp_data['decision_parameters']['apply_threshold']}%`)")
                    st.write(f"**ATS Optimization Progression**: `{exp_data['ats_score_comparison']['initial_percent']}%` ➔ `{exp_data['ats_score_comparison']['final_percent']}%` (in `{exp_data['ats_score_comparison']['iterations_run']}` iterations)")
                    
                    col_sel1, col_sel2 = st.columns(2)
                    with col_sel1:
                        st.markdown("**Selected Project Nodes**")
                        for p in exp_data["project_selection"]["selected"]:
                            st.success(f"✓ **{p['name']}**: {p['reason']}")
                    with col_sel2:
                        st.markdown("**Rejected Project Nodes**")
                        for p in exp_data["project_selection"]["rejected"]:
                            st.warning(f"✗ **{p['name']}**: {p['reason']}")
                else:
                    st.warning("No explainability log found for this application. Re-run the tailoring pipeline.")


# 3. Tab: Knowledge Graph Explorer
with tab_graph:
    st.header("Relational Knowledge Graph")
    profile = get_candidate_profile_data(db, candidate_id=1)
    
    if not profile:
        st.warning("Candidate profile not seeded. Run 'python storage/seed.py' from terminal first.")
    else:
        st.markdown(f"### Candidate: **{profile['name']}**")
        st.markdown(f"Email: {profile['email']} | GitHub: {profile['github']} | LinkedIn: {profile['linkedin']}")
        
        st.markdown("---")
        
        col_g1, col_g2 = st.columns(2)
        with col_g1:
            st.subheader("💼 Experiences")
            for exp in profile["experiences"]:
                with st.container(border=True):
                    st.markdown(f"**{exp['role']}** at **{exp['company']}** ({exp['start_date']} - {exp['end_date']})")
                    st.caption(f"Type: {exp['org_type']} | Open Source: {exp['is_open_source']}")
                    st.markdown("Bullets:")
                    for b in exp["bullets"]:
                        st.markdown(f"- {b}")
                    if exp["evidence"]:
                        st.markdown("**Evidence / Traces:**")
                        for ev in exp["evidence"]:
                            st.caption(f"- [{ev['type']}] {ev['description']} (Metrics: {ev.get('metrics') or 'N/A'})")

        with col_g2:
            st.subheader("🚀 Projects")
            for proj in profile["projects"]:
                with st.container(border=True):
                    st.markdown(f"**{proj['name']}** | {proj['category']}")
                    st.caption(f"Github: {proj['github_url']}")
                    st.markdown("Bullets:")
                    for b in proj["description_bullets"]:
                        st.markdown(f"- {b}")
                    if proj["evidence"]:
                        st.markdown("**Evidence / Traces:**")
                        for ev in proj["evidence"]:
                            st.caption(f"- [{ev['type']}] {ev['description']} (Metrics: {ev.get('metrics') or 'N/A'})")

# 4. Tab: Recruiter CRM
with tab_crm:
    st.header("Recruiter CRM Interactions")
    
    # List active applications
    apps = db.query(ApplicationTable).all()
    if not apps:
        st.info("No applications to track yet.")
    else:
        app_options = {f"{a.job.company_name} - {a.job.title}": a.id for a in apps}
        selected_app_label = st.selectbox("Select Application Interaction", list(app_options.keys()))
        selected_app_id = app_options[selected_app_label]
        
        app = db.query(ApplicationTable).filter(ApplicationTable.id == selected_app_id).first()
        
        st.markdown(f"### Tracking Recruiter logs for **{app.job.company_name}**")
        
        # Log new interaction
        st.subheader("Log a new Recruiter message")
        rec_name = st.text_input("Recruiter Name", placeholder="Jane Doe")
        rec_title = st.text_input("Recruiter Title", placeholder="Technical Recruiter")
        rec_contact = st.text_input("Contact Info", placeholder="linkedin.com/in/jane")
        
        message_sender = st.selectbox("Sender", ["Recruiter", "Candidate"])
        message_text = st.text_area("Message Content")
        
        if st.button("Log Interaction"):
            if rec_name and message_text:
                from storage.crud import save_recruiter_interaction
                msg = {
                    "sender": message_sender,
                    "text": message_text,
                    "timestamp": str(os.getenv("CURRENT_DATE", "2026-07-02"))
                }
                save_recruiter_interaction(db, app.id, rec_name, rec_title, rec_contact, msg)
                st.success("Interaction logged successfully!")
                st.rerun()

        # Display history
        if app.recruiters:
            st.markdown("---")
            st.subheader("Conversation History")
            for rec in app.recruiters:
                st.markdown(f"**Contact**: {rec.name} ({rec.title}) - {rec.contact_info}")
                history = json.loads(rec.message_history_json)
                for h in history:
                    sender_label = "👤 You" if h["sender"] == "Candidate" else "🏢 Recruiter"
                    st.info(f"**{sender_label}** ({h['timestamp']}):\n\n{h['text']}")

# 5. Tab: Offer Evaluator
with tab_offers:
    st.header("Deterministic Offer Evaluation Engine")
    st.markdown("Compare multiple offers side-by-side based on financial metrics, equity growth, remote policies, and branding.")
    
    # State-based list of offers to compare
    if 'offers' not in st.session_state:
        st.session_state['offers'] = [
            {"company_name": "Stripe (Sample)", "base_salary": 180000, "equity_annual_val": 40000, "work_policy": "Remote", "company_stage": "Late Stage"},
            {"company_name": "AI Startup (Sample)", "base_salary": 140000, "equity_annual_val": 60000, "work_policy": "Hybrid", "company_stage": "YC Seed"}
        ]
        
    # Input Form
    with st.form("add_offer_form"):
        st.subheader("Add an Offer to Compare")
        o_company = st.text_input("Company Name")
        o_salary = st.number_input("Base Salary ($)", min_value=0, value=150000)
        o_equity = st.number_input("Annual Equity Value ($)", min_value=0, value=30000)
        o_policy = st.selectbox("Work Policy", ["Remote", "Hybrid", "Onsite"])
        o_stage = st.text_input("Company Stage / Info (e.g. YC Seed, Series A, Late Stage)")
        
        submitted = st.form_submit_button("Add Offer")
        if submitted and o_company:
            st.session_state['offers'].append({
                "company_name": o_company,
                "base_salary": o_salary,
                "equity_annual_val": o_equity,
                "work_policy": o_policy,
                "company_stage": o_stage
            })
            st.success(f"Added offer from {o_company}!")
            st.rerun()
            
    # Display comparison
    if st.session_state['offers']:
        st.markdown("### Comparison Standings")
        ranked = compare_offers(st.session_state['offers'])
        
        df_ranked = pd.DataFrame(ranked)
        st.dataframe(df_ranked, use_container_width=True)
        
        # Clear button
        if st.button("Clear Offers"):
            st.session_state['offers'] = []
            st.rerun()
